# Generated by Django 5.1.4 on 2024-12-15 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.CharField(default='guest', max_length=255),
        ),
    ]
